# -*- coding: utf-8 -*-
"""sb1-peterwoo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KYapOPITdskUX8mRTtbMkHBo8hQxcTg1
"""

x = input('Input a number')
y = input('Input a second number')

print(float(x) + float(y))